version: '3.0'

expectations:
  population_size: 10000

actions:

  # TODO: switch statement for which stud(y/ies) to run?

  ####################
  # Cohort Generation
  ####################
  
  # Since this runs on everyone, we can reuse for both studies 
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv

  # Generate depression register variable among the total population by month
  generate_study_population_prevalence:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_prevalence --index-date-range "2019-01-01 to 2022-01-01 by month" --output-dir=output/qof
    outputs:
      highly_sensitive:
        cohort: output/qof/input_prevalence_*.csv

  # Generate QOF variables for those on the depression register by month
  generate_study_population_qof:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_qof --index-date-range "2019-01-01 to 2022-01-01 by month" --output-dir=output/qof
    outputs:
      highly_sensitive:
        cohort: output/qof/input_qof_*.csv
  
  # Generate depression and prescription variables (including QOF) for those with LD&A by month
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-01-01 to 2022-01-01 by month" --output-dir=output/lda
    outputs:
      highly_sensitive:
        cohort: output/lda/input_*.csv

  ####################
  # Join ethnicity to all generated input files
  # Efficiency fix https://github.com/opensafely/research-template
  # BUT BEWARE STALE DATA
  ###################

  join_qof_cohorts:
    run: >
      cohort-joiner:v0.0.6
        --lhs output/qof/input_*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/qof/joined
    needs: [generate_study_population_ethnicity, generate_study_population_prevalence, generate_study_population_qof]
    outputs:
      highly_sensitive:
        cohort: output/qof/joined/input_*.csv

  join_lda_cohorts:
    run: >
      cohort-joiner:v0.0.6
        --lhs output/lda/input_*.csv
        --rhs output/input_ethnicity.csv
        --output-dir output/lda/joined
    needs: [generate_study_population_ethnicity, generate_study_population]
    outputs:
      highly_sensitive:
        cohort: output/lda/joined/input_*.csv


  ####################
  # Measures 
  ####################
  
  # Output summary prevalence value by date
  generate_measures_prevalence:
      run: cohortextractor:latest generate_measures --study-definition study_definition_prevalence --output-dir=output/qof/joined
      needs: [join_qof_cohorts]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/qof/joined/measure_prevalence_rate.csv

  # Output the summary QOF values by date
  generate_measures_qof:
      run: cohortextractor:latest generate_measures --study-definition study_definition_qof --output-dir=output/qof/joined
      needs: [join_qof_cohorts, generate_study_population_qof]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/qof/joined/measure_qof_*_rate.csv
       

  # Output the summary LD&A values by date
  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/lda/joined
      needs: [join_lda_cohorts, generate_study_population]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/lda/joined/measure_*_rate.csv

  #############################
  # Plotting
  #############################
  generate_qof_deciles_charts:
    run: >
            deciles-charts:v0.0.1
            --input_dir output/qof/joined
            --output_dir output/qof/joined
    needs: [generate_measures_prevalence, generate_measures_qof]
    outputs:
      moderately_sensitive:
        cohort: output/qof/joined/deciles_chart_*.png

  generate_lda_deciles_charts:
    run: >
            deciles-charts:v0.0.1
            --input_dir output/lda/joined
            --output_dir output/lda/joined
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/lda/joined/deciles_chart_*.png

  generate_qof_groups:
    run: >
            python:latest analysis/group_charts.py
            --input_dir output/qof/joined
            --output_dir output/qof/joined
    needs: [generate_measures_qof]
    outputs:
      moderately_sensitive:
        cohort: output/qof/joined/group_chart_*.png

  generate_lda_groups:
    run: >
            python:latest analysis/group_charts.py
            --input_dir output/lda/joined
            --output_dir output/lda/joined
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        cohort: output/lda/joined/group_chart_*.png
