version: '3.0'

expectations:
  population_size: 10000

actions:

  ####################
  # Curation
  ####################
  generate_study_population_curation:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_curation --output-format=csv.gz --output-dir output/curation --index-date-range "2019-03-01 to 2019-03-01 by month"
    outputs:
      highly_sensitive:
        cohort: output/curation/input_curation_*.csv.gz

  generate_dataset_report_curation:
    run: >
      python:latest python analysis/dataset_report.py
        --input-files output/curation/input_curation_*.csv.gz
        --output-dir output/curation/
    needs: [generate_study_population_curation]
    outputs:
      moderately_sensitive:
        dataset_report: output/curation/input_curation_*.html

  ####################
  # Cohort Generation
  ####################

  # Since this runs on everyone, we can reuse for both studies 
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.csv.gz

  # Generate prescription variables by month
  generate_study_population_lda_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lda --index-date-range "2019-01-01 to 2019-12-01 by month" --output-format=csv.gz --output-dir output/lda/codelist_update
    outputs:
      highly_sensitive:
        cohort: output/lda/codelist_update/input_lda_2019*.csv.gz

  generate_study_population_lda_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lda --index-date-range "2020-01-01 to 2020-12-01 by month" --output-format=csv.gz --output-dir output/lda/codelist_update
    outputs:
      highly_sensitive:
        cohort: output/lda/codelist_update/input_lda_2020*.csv.gz

  generate_study_population_lda_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lda --index-date-range "2021-01-01 to 2021-12-01 by month" --output-format=csv.gz --output-dir output/lda/codelist_update
    outputs:
      highly_sensitive:
        cohort: output/lda/codelist_update/input_lda_2021*.csv.gz

  generate_study_population_lda_2022:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_lda --index-date-range "2022-01-01 to 2022-11-01 by month" --output-format=csv.gz --output-dir output/lda/codelist_update
    outputs:
      highly_sensitive:
        cohort: output/lda/codelist_update/input_lda_2022*.csv.gz

  # Generate dataset report lda
  generate_dataset_report_lda:
    run: >
      python:latest python analysis/dataset_report.py
        --input-files output/lda/codelist_update/input_*.csv.gz
        --output-dir output/lda/codelist_update
    needs: [generate_study_population_ethnicity, generate_study_population_lda_2019, generate_study_population_lda_2020, generate_study_population_lda_2021, generate_study_population_lda_2022]
    outputs:
      moderately_sensitive:
        dataset_report: output/lda/codelist_update/input_*.html

  ####################
  # Join ethnicity to all generated input files
  # Efficiency fix https://github.com/opensafely/research-template
  # BUT BEWARE STALE DATA
  ###################
  join_cohorts_lda:
    run: >
      cohort-joiner:v0.0.18
        --lhs output/lda/codelist_update/input_*.csv.gz
        --rhs output/input_ethnicity.csv.gz
        --output-dir output/lda/codelist_update/joined
    needs: [generate_study_population_ethnicity, generate_study_population_lda_2019, generate_study_population_lda_2020, generate_study_population_lda_2021, generate_study_population_lda_2022]
    outputs:
      highly_sensitive:
        cohort: output/lda/codelist_update/joined/input_*.csv.gz

  ####################
  # Measures
  ####################
  generate_measures_lda:
      run: cohortextractor:latest generate_measures --study-definition study_definition_lda --output-dir=output/lda/codelist_update/joined/
      needs: [join_cohorts_lda]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/lda/codelist_update/joined/measure_*_rate.csv

  join_measures_lda:
      run: python:latest python analysis/join_and_round.py
           --input-files output/lda/codelist_update/joined/measure_*.csv
           --output-dir output/lda/codelist_update/joined/summary
           --output-name "measure_lda.csv"
      needs: [generate_measures_lda]
      outputs:
        moderately_sensitive:
          # Only output the single summary file
          measure_csv: output/lda/codelist_update/joined/summary/measure_lda.csv

  #############################
  # Plotting
  #############################
  generate_lda_all_prescribing:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "*_all_total_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "total_population_prescribing"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --confidence-intervals
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/total_population_prescribing.png

  generate_lda_learning_disability_prescribing:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "*_learning_disability_total_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "learning_disability_prescribing"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --confidence-intervals
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/learning_disability_prescribing.png

  generate_lda_autism_prescribing:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "*_autism_total_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "autism_prescribing"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --confidence-intervals
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/autism_prescribing.png

  generate_lda_all_breakdowns:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "antidepressant_any_all_breakdown_*_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "any_antidepressant_by_demographic_group"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --exclude-group "Unknown"
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/any_antidepressant_by_demographic_group.png

  generate_lda_learning_disability_breakdown:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "antidepressant_any_learning_disability_breakdown_*_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "learning_disability_any_antidepressant_by_demographic_group"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --exclude-group "Unknown"
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/learning_disability_any_antidepressant_by_demographic_group.png

  generate_lda_autism_breakdown:
    run: >
            python:latest python analysis/panel_plots.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --measures-pattern "antidepressant_any_autism_breakdown_*_rate"
            --output-dir output/lda/codelist_update/joined/summary
            --output-name "autism_any_antidepressant_by_demographic_group"
            --date-lines "2020-03-16" "2020-12-02"
            --scale "rate"
            --exclude-group "Unknown"
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/autism_any_antidepressant_by_demographic_group.png

  generate_table1:
    run: >
            python:latest python analysis/table1.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --output-dir output/lda/codelist_update/joined/summary
            --measures-list "antidepressant_any_all_breakdown_age_band_rate"
            --measures-list "antidepressant_any_all_breakdown_sex_band_rate"
            --measures-list "antidepressant_any_all_breakdown_carehome_rate"
            --measures-list "antidepressant_any_all_breakdown_ethnicity_rate"
            --measures-list "antidepressant_any_all_breakdown_imd_rate"
            --measures-list "antidepressant_any_all_breakdown_region_rate"
            --measures-list "antidepressant_any_all_breakdown_diagnosis_rate"
            --measures-list "antidepressant_any_autism_breakdown_age_band_rate"
            --measures-list "antidepressant_any_autism_breakdown_sex_rate"
            --measures-list "antidepressant_any_autism_breakdown_carehome_rate"
            --measures-list "antidepressant_any_autism_breakdown_ethnicity_rate"
            --measures-list "antidepressant_any_autism_breakdown_imd_rate"
            --measures-list "antidepressant_any_autism_breakdown_region_rate"
            --measures-list "antidepressant_any_autism_breakdown_diagnosis_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_age_band_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_sex_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_carehome_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_ethnicity_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_imd_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_region_rate"
            --measures-list "antidepressant_any_learning_disability_breakdown_diagnosis_rate"
            --column-names "all" "learning_disability" "autism"
            --output-name "table1.html"
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/table1.html

  generate_table1_new:
    run: >
            python:latest python analysis/table1.py
            --input-file output/lda/codelist_update/joined/summary/measure_lda.csv
            --output-dir output/lda/codelist_update/joined/summary
            --measures-pattern "antidepressant_any_new_*_breakdown_*_rate"
            --column-names "all" "learning_disability" "autism"
            --output-name "table1_new.html"
    needs: [join_measures_lda]
    outputs:
      moderately_sensitive:
        cohort: output/lda/codelist_update/joined/summary/table1_new.html
